from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any

from ...agents.prompt_to_slide_agent import PromptToSlideAgent
from ...agents.speaker_notes_agent import SpeakerNotesAgent
from ...agents.quiz_generation_agent import QuizGenerationAgent
from ...agents.media_integration_agent import MediaIntegrationAgent


class OrchestrateRequest(BaseModel):
	prompt: str = Field(min_length=3)
	userId: str
	locale: str = "en"
	context: Optional[Dict[str, Any]] = None
	quiz_type: str = "comprehensive"
	audience_level: Optional[str] = None
	presentation_style: str = "educational"
	generate_images: bool = True
	generate_diagrams: bool = True


router = APIRouter()


@router.post("/orchestrate", status_code=202)
def orchestrate(body: OrchestrateRequest):
	# 1) Slides
	slides_agent = PromptToSlideAgent()
	slides_result = slides_agent.generate_slides(
		prompt_text=body.prompt,
		user_id=body.userId,
		locale=body.locale,
		context=body.context or {},
	)
	if not slides_result.get("success"):
		raise HTTPException(status_code=500, detail=slides_result.get("error", "Slide generation failed"))
	deck_id = slides_result["deck_id"]

	# 2) Speaker notes
	notes_agent = SpeakerNotesAgent()
	notes_result = notes_agent.generate_speaker_notes(
		deck_id=deck_id,
		user_id=body.userId,
		audience_level=body.audience_level,
		presentation_style=body.presentation_style,
	)
	if not notes_result.get("success"):
		raise HTTPException(status_code=500, detail=notes_result.get("error", "Speaker notes generation failed"))

	# 3) Quizzes
	quiz_agent = QuizGenerationAgent()
	quiz_result = quiz_agent.generate_quiz(
		deck_id=deck_id,
		user_id=body.userId,
		quiz_type=body.quiz_type,
		difficulty=None,
	)
	if not quiz_result.get("success"):
		raise HTTPException(status_code=500, detail=quiz_result.get("error", "Quiz generation failed"))

	# 4) Media (images and diagrams) - already generated by PromptToSlideAgent if enabled
	# But we can also generate separately if needed
	media_result = None
	if body.generate_images or body.generate_diagrams:
		try:
			media_agent = MediaIntegrationAgent()
			media_result = media_agent.generate_media_for_deck(
				deck_id=deck_id,
				context=body.context or {},
				generate_images=body.generate_images,
				generate_diagrams=body.generate_diagrams
			)
		except Exception as e:
			# Media generation is optional, don't fail the entire request
			pass

	return {
		"deckId": deck_id,
		"promptId": slides_result.get("prompt_id"),
		"quizIds": quiz_result.get("quiz_ids", []),
		"mediaGenerated": media_result.get("success", False) if media_result else False,
		"message": "Complete multimodal presentation generated successfully"
	}


