import base64
from typing import Optional, Dict, Any

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from agents.prompt_to_slide_agent import PromptToSlideAgent
from agents.speaker_notes_agent import SpeakerNotesAgent
from agents.quiz_generation_agent import QuizGenerationAgent
from agents.media_integration_agent import MediaIntegrationAgent
from exporters.ppt_exporter import PPTExporter
from utils.ppt_checks import check_no_json_tokens, check_bullets_limit


class OrchestrateRequest(BaseModel):
	prompt: str = Field(min_length=3)
	userId: str
	locale: str = "en"
	context: Optional[Dict[str, Any]] = None
	quiz_type: str = "comprehensive"
	audience_level: Optional[str] = None
	presentation_style: str = "educational"
	generate_images: bool = True
	generate_diagrams: bool = True
	estimated_slides: Optional[int] = Field(default=None, ge=3, le=30)


router = APIRouter()


@router.post("/orchestrate", status_code=202)
def orchestrate(body: OrchestrateRequest):
	# Merge context with user-provided slide estimate
	merged_context = dict(body.context or {})
	if body.estimated_slides is not None:
		merged_context["estimated_slides"] = body.estimated_slides

	# 1) Slides
	slides_agent = PromptToSlideAgent()
	slides_result = slides_agent.generate_slides(
		prompt_text=body.prompt,
		user_id=body.userId,
		locale=body.locale,
		context=merged_context,
	)
	if not slides_result.get("success"):
		raise HTTPException(status_code=500, detail=slides_result.get("error", "Slide generation failed"))
	deck_id = slides_result["deck_id"]

	# 2) Speaker notes
	notes_agent = SpeakerNotesAgent()
	notes_result = notes_agent.generate_speaker_notes(
		deck_id=deck_id,
		user_id=body.userId,
		audience_level=body.audience_level,
		presentation_style=body.presentation_style,
	)
	if not notes_result.get("success"):
		raise HTTPException(status_code=500, detail=notes_result.get("error", "Speaker notes generation failed"))

	# 3) Quizzes
	quiz_agent = QuizGenerationAgent()
	quiz_result = quiz_agent.generate_quiz(
		deck_id=deck_id,
		user_id=body.userId,
		quiz_type=body.quiz_type,
		difficulty=None,
	)
	if not quiz_result.get("success"):
		raise HTTPException(status_code=500, detail=quiz_result.get("error", "Quiz generation failed"))

	# 4) Media (images and diagrams) - already generated by PromptToSlideAgent if enabled
	# But we can also generate separately if needed
	media_result = None
	if body.generate_images or body.generate_diagrams:
		try:
			media_agent = MediaIntegrationAgent()
			media_context = dict(body.context or {})
			text_session_id = slides_result.get("metadata", {}).get("text_session_id")
			if text_session_id:
				media_context["text_session_id"] = text_session_id
			slide_deck = slides_result.get("slide_deck") or {}
			if slide_deck.get("image_markers"):
				media_context["image_markers"] = slide_deck["image_markers"]
			media_result = media_agent.generate_media_for_deck(
				deck_id=deck_id,
				context=media_context,
				generate_images=body.generate_images,
				generate_diagrams=body.generate_diagrams
			)
		except Exception as e:
			# Media generation is optional, don't fail the entire request
			pass

	# 5) Export PPT as bytes via robust pipeline and run validation checks
	ppt_bytes = None
	ppt_filename = None
	ppt_checks = {"json_tokens": [], "bullet_overflow": []}
	template_path = slides_result.get("slide_deck", {}).get("template_path") or slides_result.get("metadata", {}).get("template_path")
	try:
		# Prefer the structured deck exporter, which already uses the stored
		# slide content, speaker notes, quizzes, and media (stock images).
		exporter = PPTExporter()
		ppt_bytes, ppt_filename = exporter.export_deck_to_bytes(deck_id)
		ppt_checks["json_tokens"] = check_no_json_tokens(ppt_bytes)
		ppt_checks["bullet_overflow"] = check_bullets_limit(ppt_bytes)
	except Exception:
		ppt_bytes = None
		ppt_filename = None
		ppt_checks = {"json_tokens": ["export_failed"], "bullet_overflow": []}

	return {
		"deckId": deck_id,
		"promptId": slides_result.get("prompt_id"),
		"quizIds": quiz_result.get("quiz_ids", []),
		"mediaGenerated": media_result.get("success", False) if media_result else False,
		"pptFile": base64.b64encode(ppt_bytes).decode("utf-8") if ppt_bytes else None,
		"pptFilename": ppt_filename,
		"pptValidation": ppt_checks,
		"message": "Complete multimodal presentation generated successfully"
	}


