"""
Quiz Generation Agent: Creates interactive quizzes from slide content
Uses LLM for intelligent question generation
"""

import json
import logging
from datetime import datetime
from typing import Dict, List, Optional, Any
from dataclasses import dataclass

from ai_db import get_ai_db
from bson.objectid import ObjectId
from agents.text_generation_agent import TextGenerationAgent

logger = logging.getLogger(__name__)


@dataclass
class QuizQuestion:
	"""Structure for quiz questions"""
	question_text: str
	question_type: str  # "mcq", "fill_blank", "true_false"
	options: List[str]  # For MCQ
	correct_answer: str
	explanation: str
	difficulty: str
	topic: str


@dataclass
class Quiz:
	"""Complete quiz structure"""
	title: str
	questions: List[QuizQuestion]
	total_questions: int
	estimated_time: int  # minutes
	difficulty_level: str
	topics_covered: List[str]


class QuizGenerationAgent:
	"""Agent that generates quizzes from slide content"""
	
	def __init__(self):
		self.db = get_ai_db()
		self.slides_collection = self.db["slides"]
		self.quizzes_collection = self.db["quizzes"]
		self.text_agent = TextGenerationAgent()
		
	def generate_quiz(self, 
				 deck_id: str, 
				 user_id: str,
				 quiz_type: str = "comprehensive",
				 difficulty: Optional[str] = None,
				 num_questions: Optional[int] = None,
				 skip_db: bool = False) -> Dict[str, Any]:
		"""
		Generate quiz from slide deck
		
		Args:
			deck_id: ID of the slide deck
			user_id: User identifier
			quiz_type: "comprehensive", "per_topic", "final_only"
			difficulty: Override difficulty level
			
		Returns:
			Dict with generated quiz and metadata
		"""
		try:
			# Get slide deck
			deck = self._get_slide_deck(deck_id)
			if not deck:
				return {"success": False, "error": "Slide deck not found"}
			
			# Analyze slide content
			content_analysis = self._analyze_slide_content(deck)
				
			# Generate quiz based on type
			if quiz_type == "per_topic":
				quizzes = self._generate_per_topic_quizzes(deck, content_analysis, difficulty, num_questions)
			elif quiz_type == "final_only":
				quizzes = [self._generate_final_quiz(deck, content_analysis, difficulty, num_questions)]
			else:  # comprehensive
				quizzes = [self._generate_comprehensive_quiz(deck, content_analysis, difficulty, num_questions)]
			
			# Store quizzes (or prepare data if skip_db)
			quiz_ids = []
			quiz_data_list = []
			for quiz in quizzes:
				if skip_db:
					quiz_data = self._prepare_quiz_data(deck_id, quiz, user_id)
					quiz_data_list.append(quiz_data)
					quiz_ids.append(None)  # Will be generated by Go
				else:
					quiz_id = self._store_quiz(deck_id, quiz, user_id)
					quiz_ids.append(quiz_id)
			
			# Update slide deck with quiz references (skip if skip_db)
			if not skip_db:
				self._update_deck_quiz_refs(deck_id, quiz_ids)
			
			# Emit analytics event (skip if skip_db)
			if not skip_db:
				self._emit_analytics_event(user_id, deck_id, "quiz_generated", {
					"quiz_count": len(quizzes),
					"total_questions": sum(q.total_questions for q in quizzes),
					"quiz_type": quiz_type
				})
			
			result = {
				"success": True,
				"quiz_ids": quiz_ids,
				"quizzes": quizzes,
				"metadata": {
					"generated_at": datetime.utcnow(),
					"deck_id": deck_id,
					"quiz_type": quiz_type
				}
			}
			
			# Add prepared data for Go to store if skip_db
			if skip_db:
				result["quiz_data"] = quiz_data_list
			
			return result
			
		except Exception as e:
			return {
				"success": False,
				"error": str(e),
				"quiz_ids": []
			}
	
	def _get_slide_deck(self, deck_id: str) -> Optional[Dict]:
		"""Get slide deck from database"""
		try:
			object_id = ObjectId(deck_id)
		except Exception:
			return None
		return self.slides_collection.find_one({"_id": object_id})
	
	def _analyze_slide_content(self, deck: Dict) -> Dict[str, Any]:
		"""Analyze slide content to extract quiz-worthy concepts from final PPT content"""
		sections = deck.get("sections", [])
		bullets = deck.get("bullets", [])
		
		# Get the FINAL expanded content from PPT (this is what's actually in the slides)
		# Priority: generated_notes > expanded_content > bullets
		expanded_content = deck.get("generated_notes", [])
		if not expanded_content:
			expanded_content = deck.get("expanded_content", [])
		
		# Get original prompt for context
		original_prompt = self._get_original_prompt(deck.get("promptId"))
		
		# Extract key concepts from FINAL content (what's actually in PPT)
		concepts = []
		for idx, section in enumerate(sections):
			# Use expanded content if available, otherwise fall back to bullets
			if idx < len(expanded_content) and expanded_content[idx]:
				content_text = expanded_content[idx]
			elif idx < len(bullets) and bullets[idx]:
				# Fallback to bullets if expanded content not available
				content_text = " ".join(bullets[idx])
			else:
				continue
			
			concepts.append({
				"text": content_text,
				"section": section,
				"section_index": idx,
				"complexity": self._assess_concept_complexity(content_text),
				"bullets": bullets[idx] if idx < len(bullets) else []
			})
		
		return {
			"concepts": concepts,
			"sections": sections,
			"original_prompt": original_prompt,
			"expanded_content": expanded_content,
			"difficulty_level": deck.get("metadata", {}).get("difficulty_level", "intermediate"),
			"total_concepts": len(concepts),
			"deck_title": deck.get("title", "")
		}
	
	def _get_original_prompt(self, prompt_id: Optional[str]) -> Optional[str]:
		"""Get the original user prompt from prompts collection"""
		if not prompt_id:
			return None
		try:
			object_id = ObjectId(prompt_id)
			prompt_doc = self.db["prompts"].find_one({"_id": object_id})
			if prompt_doc:
				return prompt_doc.get("prompt_text")
		except Exception as e:
			logger.warning(f"Failed to fetch original prompt: {e}")
		return None
	
	def _assess_concept_complexity(self, text: str) -> str:
		"""Assess complexity of a concept"""
		# Simple heuristic - in production, use NLP analysis
		complex_indicators = ["analysis", "synthesis", "evaluation", "advanced", "complex"]
		simple_indicators = ["basic", "simple", "introduction", "overview"]
		
		text_lower = text.lower()
		
		if any(indicator in text_lower for indicator in complex_indicators):
			return "hard"
		elif any(indicator in text_lower for indicator in simple_indicators):
			return "easy"
		else:
			return "medium"
	
	def _generate_comprehensive_quiz(self, deck: Dict, analysis: Dict, difficulty: Optional[str], num_questions: Optional[int]) -> Quiz:
		"""Generate comprehensive quiz covering all topics with MCQs based on final PPT content"""
		concepts = analysis["concepts"]
		deck_difficulty = difficulty or analysis["difficulty_level"]
		original_prompt = analysis.get("original_prompt")
		deck_title = analysis.get("deck_title", deck.get("title", ""))
		
		# Generate MCQ questions for key concepts (always MCQ with 4 options)
		questions = []
		limit = num_questions if num_questions and num_questions > 0 else 10
		for concept in concepts[:limit]:
			question = self._generate_question_for_concept(concept, deck_difficulty, original_prompt, deck_title)
			if question:
				questions.append(question)
		
		return Quiz(
			title=f"{deck['title']} - Comprehensive Quiz",
			questions=questions,
			total_questions=len(questions),
			estimated_time=len(questions) * 2,  # 2 minutes per question
			difficulty_level=deck_difficulty,
			topics_covered=list(set(q.topic for q in questions))
		)
	
	def _generate_per_topic_quizzes(self, deck: Dict, analysis: Dict, difficulty: Optional[str], num_questions: Optional[int]) -> List[Quiz]:
		"""Generate separate quiz for each topic/section with MCQs based on final PPT content"""
		sections = analysis["sections"]
		concepts = analysis["concepts"]
		deck_difficulty = difficulty or analysis["difficulty_level"]
		original_prompt = analysis.get("original_prompt")
		deck_title = analysis.get("deck_title", deck.get("title", ""))
		
		quizzes = []
		max_per_section = None
		if num_questions and num_questions > 0 and len(sections) > 0:
			max_per_section = max(1, num_questions // len(sections))
		
		for section in sections:
			# Get concepts for this section
			section_concepts = [c for c in concepts if c.get("section") == section]
			
			if section_concepts:
				questions = []
				limit = max_per_section if max_per_section else 5
				for concept in section_concepts[:limit]:
					question = self._generate_question_for_concept(concept, deck_difficulty, original_prompt, deck_title)
					if question:
						questions.append(question)
				
				if questions:
					quiz = Quiz(
						title=f"{section} - Quiz",
						questions=questions,
						total_questions=len(questions),
						estimated_time=len(questions) * 2,
						difficulty_level=deck_difficulty,
						topics_covered=[section]
					)
					quizzes.append(quiz)
		
		return quizzes
	
	def _generate_final_quiz(self, deck: Dict, analysis: Dict, difficulty: Optional[str], num_questions: Optional[int]) -> Quiz:
		"""Generate final assessment quiz with MCQs based on final PPT content"""
		concepts = analysis["concepts"]
		deck_difficulty = difficulty or analysis["difficulty_level"]
		original_prompt = analysis.get("original_prompt")
		deck_title = analysis.get("deck_title", deck.get("title", ""))
		
		# Select most important concepts for final quiz
		limit = num_questions if num_questions and num_questions > 0 else 8
		important_concepts = concepts[:limit]
		
		questions = []
		for concept in important_concepts:
			question = self._generate_question_for_concept(concept, deck_difficulty, original_prompt, deck_title)
			if question:
				questions.append(question)
		
		return Quiz(
			title=f"{deck['title']} - Final Assessment",
			questions=questions,
			total_questions=len(questions),
			estimated_time=len(questions) * 3,  # 3 minutes per question for final
			difficulty_level=deck_difficulty,
			topics_covered=list(set(q.topic for q in questions))
		)
	
	def _generate_question_for_concept(self, concept: Dict, difficulty: str, original_prompt: Optional[str] = None, deck_title: str = "") -> Optional[QuizQuestion]:
		"""Generate a quiz question for a concept - always use MCQ with 4 options"""
		section = concept["section"]
		concept_complexity = concept.get("complexity", "medium")
		
		# Always generate MCQ questions with 4 options as requested
		return self._generate_mcq_question(concept, section, difficulty, original_prompt, deck_title)
	
	def _generate_mcq_question(self, concept: Dict, topic: str, difficulty: str, original_prompt: Optional[str] = None, deck_title: str = "") -> QuizQuestion:
		"""Generate multiple choice question with exactly 4 options based on final PPT content"""
		concept_text = concept.get("text", "")
		section_bullets = concept.get("bullets", [])
		
		# Build context from original prompt and final content
		context_text = ""
		if original_prompt:
			context_text += f"Original Topic/Prompt: {original_prompt}\n\n"
		if deck_title:
			context_text += f"Presentation Title: {deck_title}\n\n"
		context_text += f"Final Content in PPT Slide:\n{concept_text}"
		if section_bullets:
			context_text += f"\n\nKey Points:\n" + "\n".join([f"- {bullet}" for bullet in section_bullets[:5]])
		
		# Generate MCQ with exactly 4 options using LLM
		prompt = f"""Generate ONE multiple-choice question (MCQ) with EXACTLY 4 options based on the final content that appears in the PowerPoint presentation.

CRITICAL REQUIREMENTS:
1. The question MUST be based on the ACTUAL FINAL CONTENT shown below (what's in the PPT slides)
2. Generate EXACTLY 4 options (A, B, C, D)
3. Only ONE option should be correct
4. The correct answer MUST be verifiable from the final content provided
5. The other 3 options should be plausible but incorrect
6. Provide a clear explanation referencing the final content

Final Content from PPT Slide:
{context_text}

Generate a question that tests understanding of the key concepts in this final content.

Format your response as JSON:
{{
  "question": "Question text based on the final content",
  "options": [
    "Option A (correct answer)",
    "Option B (plausible but incorrect)",
    "Option C (plausible but incorrect)",
    "Option D (plausible but incorrect)"
  ],
  "correct_answer": "Option A (correct answer)",
  "explanation": "Explanation referencing the final content provided"
}}"""
		
		result = self.text_agent.generate(prompt, {"difficulty": difficulty}, max_length=1024)
		
		if result.get("success"):
			try:
				import json
				import re
				# Try to extract JSON from response
				json_match = re.search(r'\{.*\}', result["text"], re.DOTALL)
				if json_match:
					question_data = json.loads(json_match.group())
					options = question_data.get("options", [])
					
					# Ensure exactly 4 options
					if len(options) == 4:
						return QuizQuestion(
							question_text=question_data.get("question", f"Based on the content about {topic}, which of the following is correct?"),
							question_type="mcq",
							options=options,
							correct_answer=question_data.get("correct_answer", options[0] if options else ""),
							explanation=question_data.get("explanation", f"This answer is correct based on the content presented in the slide about {topic}."),
							difficulty=difficulty,
							topic=topic
						)
					else:
						logger.warning(f"LLM generated {len(options)} options instead of 4, using fallback")
			except Exception as e:
				logger.warning(f"Failed to parse MCQ question from LLM: {e}")
		
		# Fallback: Generate simple MCQ with 4 options
		# Extract key terms from concept text
		key_terms = concept_text.split()[:5]  # First 5 words as key terms
		question_text = f"Based on the content about {topic}, which of the following statements is correct?"
		
		# Generate 4 options - first one correct, others plausible but wrong
		options = [
			f"The content explains that {key_terms[0] if key_terms else 'the concept'} is important",
			f"The content states that {key_terms[1] if len(key_terms) > 1 else 'this concept'} is not relevant",
			f"The content suggests that {key_terms[2] if len(key_terms) > 2 else 'this topic'} contradicts the main idea",
			f"The content indicates that {key_terms[3] if len(key_terms) > 3 else 'this concept'} is unrelated"
		]
		
		return QuizQuestion(
			question_text=question_text,
			question_type="mcq",
			options=options,
			correct_answer=options[0],
			explanation=f"This answer is correct based on the final content presented in the slide about {topic}. The content specifically addresses this concept.",
			difficulty=difficulty,
			topic=topic
		)
	
	def _generate_true_false_question(self, concept: str, topic: str, difficulty: str) -> QuizQuestion:
		"""Generate true/false question"""
		question_text = f"True or False: {concept} is a valid concept."
		
		return QuizQuestion(
			question_text=question_text,
			question_type="true_false",
			options=["True", "False"],
			correct_answer="True",
			explanation=f"This statement is true because {concept} is indeed a valid concept.",
			difficulty=difficulty,
			topic=topic
		)
	
	def _generate_fill_blank_question(self, concept: str, topic: str, difficulty: str) -> QuizQuestion:
		"""Generate fill-in-the-blank question"""
		# Extract key term from concept
		words = concept.split()
		key_term = words[0] if words else "concept"
		
		question_text = f"Complete the following: {concept.replace(key_term, '_____')}"
		
		return QuizQuestion(
			question_text=question_text,
			question_type="fill_blank",
			options=[],
			correct_answer=key_term,
			explanation=f"The correct answer is '{key_term}' because it completes the concept accurately.",
			difficulty=difficulty,
			topic=topic
		)
	
	def _store_quiz(self, deck_id: str, quiz: Quiz, user_id: str) -> str:
		"""Store quiz in database"""
		quiz_doc = {
			"slideId": deck_id,
			"title": quiz.title,
			"questions": [
				{
					"question_text": q.question_text,
					"question_type": q.question_type,
					"options": q.options,
					"correct_answer": q.correct_answer,
					"explanation": q.explanation,
					"difficulty": q.difficulty,
					"topic": q.topic
				}
				for q in quiz.questions
			],
			"accuracy_stats": {
				"total_attempts": 0,
				"correct_attempts": 0,
				"average_score": 0.0
			},
			"live_quiz_export": None,  # Will be filled when exported to Google Forms
			"injected_position": "after_section",  # or "final"
			"metadata": {
				"total_questions": quiz.total_questions,
				"estimated_time": quiz.estimated_time,
				"difficulty_level": quiz.difficulty_level,
				"topics_covered": quiz.topics_covered,
				"generated_at": datetime.utcnow(),
				"user_id": user_id
			}
		}
		
		result = self.quizzes_collection.insert_one(quiz_doc)
		return str(result.inserted_id)
	
	def _prepare_quiz_data(self, deck_id: str, quiz: Quiz, user_id: str) -> Dict:
		"""Prepare quiz data without storing to database"""
		return {
			"slideId": deck_id,
			"title": quiz.title,
			"questions": [{
				"question_text": q.question_text,
				"question_type": q.question_type,
				"options": q.options,
				"correct_answer": q.correct_answer,
				"explanation": q.explanation,
				"difficulty": q.difficulty,
				"topic": q.topic
			} for q in quiz.questions],
			"accuracy_stats": {
				"total_attempts": 0,
				"correct_attempts": 0,
				"average_score": 0.0
			},
			"injected_position": "final",
			"metadata": {
				"total_questions": quiz.total_questions,
				"estimated_time": quiz.estimated_time,
				"difficulty_level": quiz.difficulty_level,
				"topics_covered": quiz.topics_covered,
				"generated_at": datetime.utcnow(),
				"user_id": user_id
			}
		}
	
	def _update_deck_quiz_refs(self, deck_id: str, quiz_ids: List[str]):
		"""Update slide deck with quiz references"""
		try:
			object_id = ObjectId(deck_id)
		except Exception:
			return
		self.slides_collection.update_one(
			{"_id": object_id},
			{"$set": {"quiz_refs": quiz_ids}}
		)
	
	def _emit_analytics_event(self, user_id: str, deck_id: str, event_type: str, data: Dict):
		"""Emit analytics event"""
		analytics_collection = self.db["analytics"]
		
		event_doc = {
			"userId": user_id,
			"timestamp": datetime.utcnow(),
			"deckId": deck_id,
			"event_type": event_type,
			"data": data,
			"service": "quiz_generation_agent"
		}
		
		analytics_collection.insert_one(event_doc)
